name: Bedwars
version: 2.2
api: [3.0.0, 3.1.0, 3.1.2]
main: Bluplayz\Bedwars
author: Bluplayz // Update by Assassiner354
website: http://youtube.com/Bluplayz
commands:
    Bedwars:
        description: Bedwars Main Command
        aliases: [bw]
    Start:
        description: Bedwars Forcestart Command